DROP TABLE IF EXISTS jokes;
CREATE TABLE jokes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(512) NOT NULL,
  joke VARCHAR(512) NOT NULL,
  user_name VARCHAR(512) NOT NULL,
  favorite_joke VARCHAR(512) NOT NULL
)

